# Generated by Django 5.0.2 on 2024-10-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Insira um nome valido: Nome e Sobrenomes', max_length=255, null=True)),
                ('email', models.EmailField(help_text='Insira um e-mail valido: usuario@dominio', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to='')),
                ('mensagem', models.CharField(blank=True, max_length=255, null=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('cpf_pagamento', models.PositiveBigIntegerField(help_text='Insira o CPF do pagador.', null=True)),
                ('cpf_envio', models.PositiveBigIntegerField(blank=True, help_text='Insira o CPF do cliente.', null=True)),
                ('endereco', models.CharField(blank=True, help_text='Insira o endereço do cliente.', max_length=255, null=True)),
                ('valor_produto', models.FloatField(help_text='Insira o valor do produto cotado.', null=True)),
                ('anotacoes', models.CharField(blank=True, help_text='Insira as anotacoes da cotacao', max_length=255, null=True)),
                ('envio_orcamento', models.DateField(blank=True, help_text='Insira a data do envio do orcamento.', null=True)),
                ('pagamento', models.DateField(blank=True, help_text='Insira a data do pagamento.', null=True)),
                ('conclusao', models.DateField(blank=True, help_text='Insira a data de conclusao.', null=True)),
            ],
            options={
                'verbose_name': 'Pedidos recebidos',
                'ordering': ['criacao'],
            },
        ),
    ]
